on:
  push:
    branches:
    - develop

name: Build and deploy Debug APK

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    - name: Save Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: lsp_debug
        path: app/build/outputs/apk/debug/app-debug.apk
    - name: Upload to Release
      uses: AButler/upload-release-assets@v1.0
      with:
        files: 'app-debug.apk'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
